import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./Providers";
import NavBar from "@/components/NavBar";
import { DataProvider } from "@/context/DataContext";

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DataProvider>
          <Providers>
            <NavBar />
            {children}
          </Providers>
        </DataProvider>
      </body>
    </html>
  );
}
